roles:
    - name: moc_base
      src: https://github.com/cci-moc/ansible-role-moc-base
      version: 1bae42b220
    - name: moc_firewall
      src: https://github.com/cci-moc/ansible-role-moc-firewall
      version: ab2c7be182
    - name: moc_sshd
      src: https://github.com/cci-moc/ansible-role-moc-sshd
      version: 3e65414e32
    - name: root_authorized_keys
      src: https://github.com/cci-moc/ansible-role-root-authorized-keys
      version: 2456e46a28
    - name: systemd
      src: https://github.com/cci-moc/ansible-role-systemd
      version: f0a9fea177
